### ISSUE TITLE
Illegal | You don't have permission to post this. 

### ISSUE THREAD

**Issue by jtrent238** [ShrekLeaker/OreSpawnMC#2]
Illegal | You don't have permission to post this.

**Comment by ShrekLeaker** [comment]
I know Its a leak.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DakotaDZ** [comment]
ShrekLeaker is a pussy Jtrent so yeah

**Comment by jtrent238** [comment]
@ShrekLeaker you need to delete this.

**Comment by ShrekLeaker** [comment]
I'm not deleting shit.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DakotaDZ** [comment]
trust me he seems like a 11 year old who doesnt have a girlfriend or if he does i bett shes a roblox girlfriend whose is secretly is his dad
