### ISSUE TITLE
You are a trash leaker

### ISSUE THREAD

**Issue by DakotaDZ** [ShrekLeaker/OreSpawnMC#3]
if you want to proof yourself as a good leaker leak something hard to leak, leak a sigma hacked client src, fyi sir hacks clients now these days are close to impossible to leak because of an anti leaker system.

**Comment by ShrekLeaker** [comment]
I am not going near that shit.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DakotaDZ** [comment]
than thank you for proofing my point man you are so trash get a life loser

**Comment by ShrekLeaker** [comment]
If you could get me a unFUCKed jar then please let me know!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DakotaDZ** [comment]
okay i will after you admit that you are the biggest loser your mom ever conceived

**Comment by ShrekLeaker** [comment]
You are the biggest loser your mom conceived.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DakotaDZ** [comment]
is this your best insults because i see that im winning 100%, also trust me no girl would want be fucked by you not even your 5th grade math teacher pretty sure shes giving the best blow job to some randos

**Comment by ShrekLeaker** [comment]
Want me to suck your big ol' dick?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DakotaDZ** [comment]
pretty trash insults in my opinion here some good insults instructors https://www.youtube.com/watch?v=n4UiW3RWmsw&ab_channel=ChapCharlie instead of wasting your time on leaks you should learn from him

**Comment by DakotaDZ** [comment]
i will give you a bad insult example like "I hope you forget your mask and die slowly from covid" thats a bad insult because its so long and boring that pretty much someone rather listen to teh worst song in the universe than this insult

**Comment by ShrekLeaker** [comment]
[tSCskgnBAcOwNAWAnRVJduTP.jpg]

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DakotaDZ** [comment]
wow pussy

**Comment by jtrent238** [comment]
crazy lol

**Comment by jtrent238** [comment]
why did you delete my message?

**Comment by jtrent238** [comment]
stop deleting my messages
