### ISSUE TITLE
aww

### ISSUE THREAD

**Issue by DakotaDZ** [ShrekLeaker/OreSpawnMC#4]
did i hurt your feeling bitch

**Comment by ShrekLeaker** [comment]
I got something to leak YOUR IP!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DakotaDZ** [comment]
tough luck you are useless i bettt your dad went for milk because he didnt wanna be your dad such embarrassment

**Comment by ShrekLeaker** [comment]
Click this link >>> [https://grabify.link/LLJRUL](https://grabify.link/LLJRUL) ![](https://grabify.link/LLJRUL.png)

**Comment by DakotaDZ** [comment]
bruh im not that stupid dumb fuck

**Comment by DakotaDZ** [comment]
omg i accidentally clicked on it
please

**Comment by DakotaDZ** [comment]
please im crying dont leak it

**Comment by ShrekLeaker** [comment]
You used a fucken proxy.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ShrekLeaker** [comment]
![](https://i.imgur.com/TbPNIUd.png)

**Comment by DakotaDZ** [comment]
get fucked punk

**Comment by DakotaDZ** [comment]
well i live in ontario canada

**Comment by ShrekLeaker** [comment]
Im going to leak [this](https://www.curseforge.com/minecraft/mc-mods/killer-pacman#c8) mod

**Comment by DakotaDZ** [comment]
okay fine i went and saw what was that bs you happy now daddy

**Comment by DakotaDZ** [comment]
i had to see what was the grabify link

**Comment by jtrent238** [comment]
> okay fine i went and saw what was that bs you happy now daddy

what was what?

**Comment by DakotaDZ** [comment]
listen here punk i know you are some weird toxic or super fan if you want my photograph or jt's graph here it is mine aka Dakota

from dakota to the dumb fuckery love please stop doing dumbshit dipshit

**Comment by ShrekLeaker** [comment]
![](https://i.imgur.com/MxJl7VF.png)

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ShrekLeaker** [comment]
![](https://i.imgur.com/MxJl7VF.png)
